language: python

sudo: required
dist: trusty

python:
  - "2.7_with_system_site_packages"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq swig openbabel python-openbabel

script: nosetests
